### ISSUE TITLE
import fix

### ISSUE THREAD

**Issue by Alexey-T** [philadams-zz/dimensions#1]
i use in my code. i place folder `dimensions` to path (sys.path) and now have error
"Cannot import JPGFile"

fix is this

```
from . import PNGFile
from . import GIFFile
from . import JPEGFile
```

in core.py.
import from .!!

**Comment by philadams-zz** [comment]
Hi Alexey!

Either with the project's dimensions folder on sys.path, or with dimensions installed (`pip install dimensions`), I'd recommend either of the following interfaces:

Using `dimensions.dimensions`:

```
>>> from dimensions import dimensions as dims
>>> fname = '/Users/phil/Desktop/screenshot.png'
>>> dims(fname)
(310, 126, 'image/png', '/Users/phil/Desktop/screenshot.png')
>>> dims([fname, ])
[(310, 126, 'image/png', '/Users/phil/Desktop/screenshot.png')]
```

Using PNGFile directly:

```
>>> from dimensions.PNGFile import PNGFile
>>> PNGFile(open(fname)).size
(310, 126)
>>> PNGFile(open(fname)).content_type
'image/png'
```

Will that work?

**Comment by Alexey-T** [comment]
if Py3 works. it doesnt :\

**Comment by philadams-zz** [comment]
Gothca - I'll take a look at Py3 asap - hopefully over the weekend.
