### ISSUE TITLE
Py3!!

### ISSUE THREAD

**Issue by Alexey-T** [philadams-zz/dimensions#2]
pls support Py3.2. I see "Cannot import StringIO" and see this

https://docs.python.org/3.0/whatsnew/3.0.html

StringIO and cStringIO modules are gone. Instead, import the io module and use io.StringIO or io.BytesIO for text and data respectively.

**Comment by Alexey-T** [comment]
```
"cannot handle file: C:\Arc\path\imagetest.png" 
```

still BAD. In py3.2, Win7.

**Comment by philadams-zz** [comment]
I'll take a look at this - thanks. Honestly, I don't really use Python 3.x yet as I'm quite dependent on a couple big third party open source modules that are still 2.x-based.

**Comment by Alexey-T** [comment]
--big-- work needed

**Comment by philadams-zz** [comment]
Apologies - dissertation got in the way of updates! Please do feel free to make a pull request yourself :)

**Comment by Alexey-T** [comment]
No thanks: i don't need now
